language: node_js # JavaScript.
node_js:
 - '17'

cache:
  directories:
    - node_modules
    - ~/.npm

git:
  depth: 3

script:
  - yarn build

deploy:
  provider: pages # GitHub Pages.
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB-TOKEN

  local-dir: dist/
  target-branch: gh-pages
  commit-message: "Deploy del proyecto!"
  on:
    branch: master
